[[plugins]]
repo = 'Shougo/neocomplete'

[[plugins]]
repo = 'Shougo/echodoc.vim'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'pirosikick/vim-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'Quramy/tsuquyomi'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/open-browser-github.vim'

[[plugins]]
repo = 'tikhomirov/vim-glsl'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'zerowidth/vim-copy-as-rtf'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'mustache/vim-mustache-handlebars'

[[plugins]]
repo = 'w0rp/ale'
