# Prefix
#set-option -g prefix C-z

# Reload .tmux.conf
bind C-r source-file ~/.config/tmux/.tmux.conf

set -g default-shell $SHELL

# http://blog.monochromegane.com/blog/2013/12/12/tmux-no-prefix/
bind -n S-up select-pane -U
bind -n S-down select-pane -D
bind -n S-left select-pane -L
bind -n S-right select-pane -R

# http://qiita.com/okuramasafumi/items/72f61ec0af56b7b9b292
if-shell "tmux -V | grep '1.9'" "unbind %; bind-key % split-window -h -c \"#{pane_current_path}\"; unbind '\"'; bind-key '\"' split-window -v -c \"#{pane_current_path}\""

set -g status-interval 10

# Set statusbar colors
set -g status-bg colour9
setw -g window-status-current-style bg="white",fg="black"

# Enable mouse
set -g mouse on
bind -n WheelUpPane   select-pane -t= \; copy-mode -e \; send-keys -M
bind -n WheelDownPane select-pane -t= \;                 send-keys -M

# Enable vi keybindings in copy mode
setw -g mode-keys vi

# Configure copy mode for vim-like selections
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection \; run-shell "tmux save-buffer - | pbcopy"   # macOS

# Paste from clipboard using C-p
bind-key C-p run-shell "tmux show-buffer | pbcopy"   # macOS

# Ensure system clipboard support is enabled
set-option -g set-clipboard on

# zshのkeybindと被っているので削除
unbind-key -n C-r
unbind-key -n C-]

# https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95
set-option default-terminal "tmux-256color"

